List f1Countries = [
  {"name": "Australia", "code": "AU"},
  {"name": "Austria", "code": "AT"},
  {"name": "Azerbaijan", "code": "AZ"},
  {"name": "Bahrain", "code": "BH"},
  {"name": "Belgium", "code": "BE"},
  {"name": "Brazil", "code": "BR"},
  {"name": "Canada", "code": "CA"},
  {"name": "China", "code": "CN"},
  {"name": "France", "code": "FR"},
  {"name": "Germany", "code": "DE"},
  {"name": "Hungary", "code": "HU"},
  {"name": "Italy", "code": "IT"},
  {"name": "Japan", "code": "JP"},
  {"name": "Mexico", "code": "MX"},
  {"name": "Monaco", "code": "MC"},
  {"name": "Netherlands", "code": "NL"},
  {"name": "Qatar", "code": "QA"},
  {"name": "Saudi Arabia", "code": "SA"},
  {"name": "Singapore", "code": "SG"},
  {"name": "Spain", "code": "ES"},
  {"name": "United Arab Emirates", "code": "AE"},
  {"name": "United Kingdom", "code": "GB"},
  {"name": "USA", "code": "US"},
  //
  {"name": "Argentina", "code": "AR"},
  {"name": "India", "code": "IN"},
  {"name": "Malaysia", "code": "MY"},
  {"name": "Portugal", "code": "PT"},
  {"name": "Russia", "code": "RU"},
  {"name": "South Africa", "code": "ZA"},
  {"name": "South Korea", "code": "KR"},
  {"name": "Sweden", "code": "SE"},
  {"name": "Switzerland", "code": "CH"},
  {"name": "Turkey", "code": "TR"},
];
